### ISSUE TITLE
Try cross-country wealth index calculation for the 4 DHS countries

### ISSUE THREAD

**Issue by tm-kah-alforja** [thinkingmachines/unicef-ai4d-poverty-mapping#102]

**Comment by tm-kah-alforja** [comment]
Able to get pooled recalculated wealth indices after combining the 4 DHS countries; results are the ff:

- Recomputing leads to having very different wealth distributions per country. Cambodia now appears to be a lot poorer than the other 3 countries based on the calculation
- this temporarily uses the same defaults as the geowrangler tutoriaL, but the function accepted a list of features

**Comment by alronlam** [comment]
Action Items:
* Wrap-up on the notebook to document the wealth index re-calculation issues.
* Check the standard list of features used per country, validate that we can re-create the wealth index per country.
* Find what's the common set of features for the 4 countries, then re-calculate based on that.

**Comment by tm-kah-alforja** [comment]
- [ ] next step: debug column mapping

**Comment by tm-kah-alforja** [comment]
Cambodia drinking water column:

- It turns out that for Cambodia, there are actually two columns for drinking water, one for dry/wet season. (The other countries combine this into one column)

- There's also a column indicating if it's the same source for both seasons (10k out of 16k have the same source)


Next steps:
- [ ] normalize wealth index recalculation from 0-1
- [ ] after computing cross country pooled index, perform validations per country
