### ISSUE TITLE
data preparation

### ISSUE THREAD

**Issue by tm-amber-yaokasin** [thinkingmachines/unicef-ai4d-poverty-mapping#11]
DHS Data

- [x] Philippines
- [x] Cambodia
- [x] Myanmar
- [x] Timor Leste

OSM

- [x] Philippines
- [x] Cambodia
- [x] Myanmar
- [x] Timor Leste
- [x] Laos
- [x] Malaysia
- [x] Thailand
- [x] Vietnam
- [x] Indonesia

Ookla

- [x] Philippines
- [x] Cambodia
- [x] Myanmar
- [x] Timor Leste
- [x] Thailand
- [x] Laos
- [x] Malaysia
- [x] Vietnam
- [x] Indonesia

NTL
- [x] Philippines
- [x] Cambodia
- [x] Myanmar
- [x] Timor Leste
- [x] Laos
- [x] Malaysia
- [x] Thailand
- [x] Vietnam
- [x] Indonesia

**Comment by tm-amber-yaokasin** [comment]
- [ ] #33 
- [ ] #34 
- [ ] #35 
- [ ] #36

**Comment by tm-amber-yaokasin** [comment]
- [ ] #37

**Comment by tm-amber-yaokasin** [comment]
For NTL processing 

- Compare QGIS with Python 
- Investigate discrepancies

**Comment by tm-kah-alforja** [comment]
- [ ] #53
