### ISSUE TITLE
Cross-country experiments: Normalize each feature per country along with the wealth index

### ISSUE THREAD

**Issue by tm-kah-alforja** [thinkingmachines/unicef-ai4d-poverty-mapping#112]

**Comment by alronlam** [comment]
Updates from Jace:

Using scaled features and scaled wealth index (per-country) improves our cross-country performance!

More details here:
https://docs.google.com/document/d/1BrVgLLun48z2iitScisOr1F62b2uedWp1ihN3Qqbp0I/edit#heading=h.4ihvh46o55bc
