### ISSUE TITLE
Add a feature engineering module for quick re-use across training and rollout notebooks

### ISSUE THREAD

**Issue by tm-kah-alforja** [thinkingmachines/unicef-ai4d-poverty-mapping#142]
implement scaler step within utils

**Comment by alronlam** [comment]
Done:
- Refactor Timor Leste notebook.

ToDo:
- Open PR for timor-leste feedback. Once approved and merged, replicate for other 3 countries.

Blockers/Questions:
- Single-country: 4 diff notebooks doing the exact same thing. Already have a notebook for Timor-Leste.  Question: Do all 4 and open PR, or open PR for Timor Leste now to get feedback/do revisions then execute on remaining 3 countries.
