### ISSUE TITLE
Pytest + Geopandas not in requirements

### ISSUE THREAD

**Issue by AnthonyMockler** [thinkingmachines/unicef-ai4d-poverty-mapping#185]
Trying to run the tests, followed the install instructions in readme, but when I run 'make test' it says 
`make: pytest: No such file or directory
make: *** [test] Error 1
`

Manually installing (via conda or pip) requirements-dev.txt resolves this.

**Recommendation:**

* Update README to include the workflow for installing dev requirements using conda / mamba
* Add a CI step that includes running the provided setup workflow and making sure the tests run

**Comment by alronlam** [comment]
Verified as of merged PR: https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping/pull/198 that the requirements were fixed (it is now streamlined to just follow one file; no more requirements-dev as this isn't prod software anyway).
