### ISSUE TITLE
Parametrize / automate `process_string` parameter in nightlights module

### ISSUE THREAD

**Issue by tm-jc-nacpil** [thinkingmachines/unicef-ai4d-poverty-mapping#77]
Hi @butchtm , just wanted to flag for future improvements. I have a feeling the `process_suffix`  will change depending if they have changes in the preprocessing stages. It's possible that they will upload new versions, with a different process_suffix. In that case, since it's hardcoded, we might not find the correct url. 

Possible Solution
- could we parametrize make_url to accept a custom process_string ? 

_Originally posted by @tm-jc-nacpil in https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping/pull/75#discussion_r1070847302_

**Comment by butchtm** [comment]
implement as per request!
