### ISSUE TITLE
Decide on appropriate tile size for training

### ISSUE THREAD

**Issue by tm-kah-alforja** [thinkingmachines/unicef-ai4d-poverty-mapping#86]

**Comment by alronlam** [comment]
Meta RWI Study:
* Paper https://arxiv.org/ftp/arxiv/papers/2104/2104.07761.pdf
* Output files https://data.humdata.org/dataset/relative-wealth-index

Checked the file and saw they were using Bing tile Zoom level 14.

**Comment by alronlam** [comment]
https://www.nature.com/articles/s41467-020-16185-w#Sec10  
Yeh - 6.72 km 


https://www.sciencedirect.com/science/article/pii/S2666389922002252 
Zoom level of studies that used image data ranged from google maps api zoom level 14-17.

**Comment by tm-kah-alforja** [comment]
Final recommendation is to use 2.4km tile resolution.
